[global]
developmentMode = false

[server]
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
